### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by Lyla-Fischer** [ahopkins/pydiggy#3]
* PyDiggy version: Latest master
* Python version: 3.7.3
* Operating System: Ubuntu 16.04

### Description

I was just trying to download the code and run the tests

### What I Did

```
pipenv shell
pipenv sync -d
make test
```

I see that a lot of the development notes still have references to virtualenv, virtualenvwrapper, etc. Maybe there is something wrong with the creation of the Pipfile or the Pipfile.lock file so that there are missing dependencies?

**Comment by ahopkins** [comment]
@Lyla-Fischer Perhaps. I also would not be surprised if I have some test fixes sitting on my other computer waiting to be pushed to the repo. I'll respond more fully in #2.

**Comment by Lyla-Fischer** [comment]
Thanks for the progress on the failing tests! I'm still not able to run `make test`, though. I noticed that in fixing the tests, you didn't update Pipfile.lock (only Pipfile), which is the file that `pipenv sync` looks at. 

For reference, the error that I am getting when I try to run tests is 
```
self = <[AttributeError("'Region' object has no attribute 'uid'") raised in repr()] Region object at 0x7eff6124b438>

    def _generate_uid(self) -> str:
>       i = next(self._i)
E       TypeError: 'count' object is not an iterator

pydiggy/node.py:661: TypeError
```

**Comment by ahopkins** [comment]
That error specifically was because there was a variable that was overriding `count`. That code should be fixed. 🤔

https://github.com/ahopkins/pydiggy/blob/master/pydiggy/node.py#L13

Are you sure you have all the recent changes?

**Comment by Lyla-Fischer** [comment]
Ah - it looks like you missed one that only showed up when tests are run back-to-back. I opened a quick pull request with the one-liner update. First pull request!
